sudo: required
services:
  - docker
before_install:
  - docker-compose -f docker-compose-prod.yml up --build -d
script:
  - echo "OK" #测试单个module
  - echo "OK2" #集合测试
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push aleczheng/vb-front
  - docker push aleczheng/vb-backend
deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: virtualbooth
  env: "Virtualbooth-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-994743087499"
  bucket_path: "virtualbooth"
  on:
    branch: master
  access_key_id: $BEANSTALK_ID
  secret_access_key: $BEANSTALK_TOKEN
